CREATE TABLE usuario (
	cod SERIAL PRIMARY KEY,
	nome VARCHAR(150) NOT NULL,
	cpf VARCHAR(14) UNIQUE NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	senha VARCHAR(16) NOT NULL,
	telefone VARCHAR(16),
	tipo_usuario VARCHAR(16) NOT NULL
);

CREATE TABLE serie (
	cod INTEGER PRIMARY KEY,
	nome VARCHAR(80) NOT NULL, 
	modalidade VARCHAR(30) NOT NULL
);

CREATE TABLE turma (
	cod INTEGER PRIMARY KEY,
	sigla VARCHAR(10) NOT NULL,
	serie INTEGER NOT NULL,
	professor INTEGER NOT NULL, 
	FOREIGN KEY (serie) REFERENCES serie(cod)
	ON UPDATE CASCADE ON DELETE RESTRICT, 
	FOREIGN KEY (professor) REFERENCES usuario(cod)
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE disciplina (
	cod INTEGER PRIMARY KEY,
	nome VARCHAR(150) NOT NULL
);

CREATE TABLE turma_disciplina (
	turma INTEGER NOT NULL,
	disciplina INTEGER NOT NULL, 
	PRIMARY KEY (turma, disciplina),
	FOREIGN KEY (turma) REFERENCES turma(cod)
	ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (disciplina) REFERENCES disciplina(cod)
	ON UPDATE CASCADE ON DELETE RESTRICT
);
